### ISSUE TITLE
segfault on Fedora 25

### ISSUE THREAD

**Issue by tuxmaster** [Unode/firefox_decrypt#10] opened 2017-02-07 14:52 UTC
LANG=C python firefox_decrypt.py  -vvv /tmp/A
2017-02-07 15:51:23,167 - DEBUG - Parsed commandline arguments: Namespace(choice=None, export_pass=False, list=False, no_interactive=False, profile='/tmp/A', verbose=3)
2017-02-07 15:51:23,167 - DEBUG - Skipping password store test, not exporting
2017-02-07 15:51:23,167 - DEBUG - Loading NSS library from libnss3.so
2017-02-07 15:51:23,168 - DEBUG - Reading profiles from /tmp/A/profiles.ini
2017-02-07 15:51:23,169 - WARNING - profile.ini not found in /tmp/A
2017-02-07 15:51:23,169 - WARNING - Continuing and assuming '/tmp/A' is a profile location

Master Password for profile /tmp/A: 
2017-02-07 15:51:34,030 - DEBUG - Initializing NSS with profile path '/tmp/A'
2017-02-07 15:51:34,035 - DEBUG - Initializing NSS returned 0
2017-02-07 15:51:34,035 - DEBUG - Retrieving internal key slot
2017-02-07 15:51:34,035 - DEBUG - Internal key slot -1299103056
2017-02-07 15:51:34,036 - DEBUG - Authenticating with password 'lll'
Segmentation fault (core dump)

**Comment by Unode** [comment] 2017-02-07 14:56
Hi tuxmaster,

I'm not sure I understand the use of `LANG=C` but in any case, have a look at #2 and #9.
And please provide a little more information about versions of libraries your are using.

**Comment by Unode** [comment] 2017-02-07 15:59
Hi tuxmaster, I'm classifying this as a duplicate of #9. Moving the discussion there.

**Closed by Unode** 2017-02-07 15:59 UTC
Labels: duplicate
