### ISSUE TITLE
Sometimes usernames are not reported in output result

### ISSUE THREAD

**Issue by Reversing26** [unode/firefox_decrypt#83] opened 2022-03-20 12:56 UTC
Just tested against Firefox ESR 91.0
Example:
Website: "https://mylogin.com"
Username: ""
Password:"Mypass982."

Username/E-mail sometimes is not retrieved. It happens randomly.

**Comment by Reversing26** [comment] 2022-03-20 12:58
My Python version is 3.9.8 amd64

**Comment by unode** [comment] 2022-03-20 20:22
That's a curious one, but let me see if I understand correctly.
When you say "sometimes" does this mean, "some records show, some don't" or "the same record sometimes shows and sometimes doesn't"?

To confirm, if you open Firefox's password management dialog, do you see a username in that record?

**Comment by Reversing26** [comment] 2022-03-21 01:27
Some records show, some don't
I confirm, I have username saved in my password manager and no master password is active

**Comment by unode** [comment] 2022-03-21 12:12
Can you replicate this in a new Firefox profile (and attach it)?

I can't replicate the behavior on my side.

**Comment by Reversing26** [comment] 2022-03-21 20:30
Microsoft Windows [Version 10.0.19042.844]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cd c:/users/Reversing26/onedrive/desktop/firefox_decrypt

c:\Users\Reversing26\OneDrive\Desktop\firefox_decrypt>firefox_decrypt.py
2022-03-21 21:19:25,399 - WARNING - Running with unsupported encoding 'locale': cp1252 - Things are likely to fail from here onwards
Select the Mozilla profile you wish to decrypt
1 -> Profiles/21cwly2w.default-esr
2 -> Profiles/5wce13si.default
3 -> Profiles/wayit2sf.default-release
1

Website:   https://website.com
Username: ''
Password: 'Hiddenpassword.com'

Website:   https://website.com
Username: 'username@hotmail.com'
Password: 'HiddenpasswordDD.com'

Website:   https://www.website1.com
Username: 'username1@live.com'
Password: 'HiddenPassword1.com'

Website:   https://www.website2.com
Username: 'userw22e@live.com'
Password: 'HiddenPassword2.com'

Website:   https://www.website3.com
Username: 'hello@live.com'
Password: 'HiddenPassword3.com'

Website:   https://www.website4.com
Username: 'hello2@live.com'
Password: 'HiddenPassword332.com'

Website:   https://www.website222.com
Username: 'displayed@live.com'
Password: 'HiddenPassword838.com'

Website:   https://website37237.com
Username: ''
Password: 'HiddenPassword37372.com'

Website:   https://myloveforever.com
Username: ''
Password: 'HiddenPassword37272.com'

Website:   https://website3838.com
Username: 'displayed@output.com'
Password: 'HiddenPassword.com'

Website:   https://www.website3831.com
Username: ''
Password: 'HiddenPassword3828.com'

Website:   https://www.websitehello.com
Username: 'displayed@hello.com'
Password: 'HiddenPassword3723672'

Website:   https://website43.com
Username: ''
Password: 'Pass283834'

Website:   https://fileless.com
Username: 'fileless'
Password: 'HiddenPsw.com'

Website:   https://webmail.com
Username: 'noemail@hotmail.com'
Password: 'HiddMail.com'

Website:   https://sophia.unicusano.it
Username: 'Hiddemail@live.com'
Password: 'HiddPsw'

Website:   https://www.infinity.com
Username: ''
Password: 'ndnausnduaunsdaus'

Website:   https://www.infinity.com
Username: 'Nomail@user.com'
Password: 'Useless.'

**Comment by unode** [comment] 2022-03-22 11:58
Can you zip your profile and attach it here? I don't see any reason for this to fail in some but not others...

**Comment by unode** [comment] 2022-05-16 07:49
I can't reproduce this error so I will close it.
If you can see this consistently, please attach your profile.

**Closed by unode** 2022-05-16 07:49 UTC
