### ISSUE TITLE
Error - Passwords protected by a Master Password!

### ISSUE THREAD

**Issue by yermulnik** [Unode/firefox_decrypt#3] opened 2016-01-16 14:44 UTC
While trying to export my passwords I get an error: ```Error - Passwords protected by a Master Password!```
I'm sure I enter correct master password. What is the culprit?

Full output:
```
Select the Firefox profile you wish to decrypt
1 -> bgpdiy8n.default-1373553171844
Choice: 1

Master Password for profile /home/yz/.mozilla/firefox/bgpdiy8n.default-1373553171844:
Info - Using /home/yz/.mozilla/firefox/bgpdiy8n.default-1373553171844/logins.json for credentials.
Error - Passwords protected by a Master Password!
```

**Comment by Unode** [comment] 2016-01-18 14:20
Hi George,

I can only imagine this being a encoding/decoding problem.

Can you try the following patch and see if it works for you?

    diff --git a/firefox_decrypt.py b/firefox_decrypt.py
    index 2192ad2..9342142 100755
    --- a/firefox_decrypt.py
    +++ b/firefox_decrypt.py
    @@ -206,7 +206,7 @@ def ask_password(profile):
         Prompt for profile password
         """
         passmsg = "\nMaster Password for profile {}: ".format(profile)
    -    return getpass(passmsg)
    +    return getpass(passmsg).decode(sys.stdin.encoding).encode("utf8")
     
     
     def main():

**Comment by yermulnik** [comment] 2016-01-18 14:38
Doesn't help =( Same error.
Maybe it could be a matter: there're special chars in my Master Password.

**Comment by Unode** [comment] 2016-01-18 14:40
Can you tell me what this returns on your system?

    python -c "import sys; print sys.stdin.encoding"

**Comment by yermulnik** [comment] 2016-01-18 14:43
`UTF-8`

**Comment by Unode** [comment] 2016-01-18 14:48
Yeah so the patch changed nothing.
I can only see this as a problem when passing the bytes to `nss`. Encoding or something of the kind.
I'll see if I can figure out the right way to do it. I need to reproduce it on my system first.

**Comment by yermulnik** [comment] 2016-01-18 14:57
Thanx. Tell me if you'll need any additional data or actions on my side.

**Comment by Unode** [comment] 2016-01-18 17:19
Hi George,

While testing with a bunch of random usernames and passwords with special characters (including non-latin alphabets) I managed to reproduce the problem once. However it worked again after trying to reduce the list and I didn't manage to reproduce it since. Sadly I didn't keep a backup of the broken state.

It definitely looks related to special characters both on username and/or password fields. Having a master password with special characters might also influence. Couldn't clear that one out yet.

A few of things I'd like you to try:

1. Make a backup of your Firefox profile to keep the bad state in case it starts working after the tests.

2. Remove your master password from the keychain using Firefox. Try using firefox_decrypt entering no Master Password and see if it still fails.

3. Restore the same Master Password you had before and try firefox_decrypt again.

4. If after this it still fails, try removing some logins from the credentials database and keep retrying with firefox_decrypt. If it starts working try re-logging on the same website with the removed credentials and re-add them to the database. See if firefox_decrypt stops working again.

Thanks

**Comment by yermulnik** [comment] 2016-01-18 20:31
Steps 1-3 - no luck =( I even tried to set simple password (w/o special chars).
Step 4 - it's gonna be kinda challenge: I've got 1066 logins in my database =) I'll take a look if it's possible to wipe some unneeded data.

**Comment by yermulnik** [comment] 2016-01-18 21:39
I gave up wiping passwords after the first hundred =) And decided to do some debugging:
```python
...
            if libnss.PK11SDR_Decrypt(byref(username), byref(outuser), None) == -1:
                err.write("Error - Passwords protected by a Master Password!\n")
                error = libnss.PORT_GetError()
                libnss.PR_ErrorToString.restype = c_char_p
                error_str = libnss.PR_ErrorToString(error)
                err.write("[DEBUG] %d: %s\n" % (error, error_str))
                return 8
...
```
And here's what I got:
```shell
23:24:47 [yz@local][w:4][j:0][~/.../CODE/firefox_decrypt]> ./firefox_decrypt.py
Select the Firefox profile you wish to decrypt
1 -> bgpdiy8n.default-1373553171844
Choice: 1

Master Password for profile /home/yz/.mozilla/firefox/bgpdiy8n.default-1373553171844:
Info - Using /home/yz/.mozilla/firefox/bgpdiy8n.default-1373553171844/logins.json for credentials.
Error - Passwords protected by a Master Password!
[DEBUG] -5977: Failure to load dynamic library
```
I ran `strace` and found "lost" library:
```
open("/home/yz/.mozilla/firefox/bgpdiy8n.default-1373553171844/libnssckbi.so", O_RDONLY|O_CLOEXEC) =  -1 ENOENT (No such file or directory)
```
I found `/usr/lib/firefox/libnssckbi.so` and `/usr/lib/x86_64-linux-gnu/nss/libnssckbi.so` on my sandbox. So I symlinked both of them in turn into my FF profile's directory, but both libs produced the same error:
`[DEBUG] -8015: The certificate/key database is in an old, unsupported format.`
And it's where Ive stuck =(

**Comment by Unode** [comment] 2016-01-19 13:29
Hum... on my system `libnss3.so` doesn't have any links to `libnssckbi.so`.
I'm using `nss-3.20.1`.

    % ldd /usr/lib64/libnss3.so
        linux-vdso.so.1 (0x00007ffe12789000)
        libnssutil3.so => /usr/lib64/libnssutil3.so (0x00007f539ea1f000)
        libplc4.so => /usr/lib64/libplc4.so (0x00007f539e81a000)
        libplds4.so => /usr/lib64/libplds4.so (0x00007f539e615000)
        libnspr4.so => /usr/lib64/libnspr4.so (0x00007f539e3d7000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f539e027000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f539de09000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f539dc05000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f539d9fd000)
        /lib64/ld-linux-x86-64.so.2 (0x00005640166d1000)

What version of nss is yours and distribution by the way? (Sabayon here)

**Comment by yermulnik** [comment] 2016-01-19 14:00
> Hum... on my system libnss3.so doesn't have any links to libnssckbi.so.

Just run `strace ./firefox_decrypt.py` and you'll see those library call...

> What version of nss is yours and distribution by the way? (Sabayon here)

LInux Mint 17.1 Rebecca 
ii  libnss3:amd64       2:3.19.2.1-0ub amd64          Network Security Service libraries
ii  libnss3:i386        2:3.19.2.1-0ub i386           Network Security Service libraries

**Comment by Unode** [comment] 2016-01-19 14:55
You are right, the `strace` log does include a check for `libnssckbi.so` but its non-fatal. It's not found on my system either.

I've included the debugging snippet you mentioned here and credited accordingly, thanks for the suggestion.

Does your strace log show anything relevant after the lookup error?

**Comment by yermulnik** [comment] 2016-01-19 15:47
> You are right, the strace log does include a check for libnssckbi.so but its non-fatal.

But it did fail because of that library not being in path.

> Does your strace log show anything relevant after the lookup error?

Nope =( And google can't help =(
```
 [DEBUG] -8015: The certificate/key database is in an old, unsupported format.
```

**Comment by Unode** [comment] 2016-01-19 16:45
Indeed, the only things that pop up on google with that message are references to users that did not have all the required files from the firefox profile folder. Doesn't seem to be your case since you are using the profile folder directly.

One last thing to try is to create a new profile and test if firefox_decrypt can read that one. Use `firefox -ProfileManager -no-remote`.

If it can it's definitely something specific to your profile folder.
If it cannot, then there's for sure a bug creeping somewhere on the nss stack.

**Comment by Unode** [comment] 2016-01-20 11:51
Hi again,

So it seems #2 shares some of the symptoms except in that case it segfaults early on.
Definitely something weird is going on when interacting with NSS. More testing for later...

**Comment by Unode** [comment] 2016-02-16 12:14
Hi George,

I was recently converting the script to be compatible with python 3 and I got the same error you got before:

     [DEBUG] -8015: The certificate/key database is in an old, unsupported format.

I always got this as long as I passed the profile location as unicode to the nss library. Forcing a `profile.encode("utf8")` call fixed it. Just wondering if that was also the case for you.

**Comment by yermulnik** [comment] 2016-02-16 12:42
Where should I place this code?

**Comment by Unode** [comment] 2016-02-16 13:14
I'll push some code in a while. I'll notify you here. If you could check if it helps your problem it would be great.

**Comment by yermulnik** [comment] 2016-02-16 13:45
Ok, thanx!

**Comment by Unode** [comment] 2016-02-16 15:40
Pushed.

**Comment by yermulnik** [comment] 2016-02-16 16:12
No luck =(
```
18:11:05 [yz@local][w:4][j:0][~/.../CODE/firefox_decrypt]> git pull origin
Already up-to-date.
18:11:17 [yz@local][w:4][j:0][~/.../CODE/firefox_decrypt]> ./firefox_decrypt.py
Select the Firefox profile you wish to decrypt
1 -> bgpdiy8n.default-1373553171844
Choice: 1

Master Password for profile /home/yz/.mozilla/firefox/bgpdiy8n.default-1373553171844:
2016-02-16 18:11:26,795 - ERROR - Passwords protected by a Master Password!
```

**Comment by Unode** [comment] 2016-02-16 16:14
Can you try with `python3` and with higher verbosity level `-vv`?
Check if you spot anything strange about your password or any of the output.

**Comment by yermulnik** [comment] 2016-02-16 17:03
`/usr/bin/env python3 -vv ./firefox_decrypt.py` - output attached
[firefox_decrypt.log.txt](https://github.com/Unode/firefox_decrypt/files/132933/firefox_decrypt.log.txt)

**Comment by Unode** [comment] 2016-02-16 17:32
:( the trace doesn't include anything useful.

I don't understand how the `NSS_Init` step is simply ignored. It doesn't fail but it also doesn't succeed.
Could you perhaps change the line containing `if NSS.NSS_Init(...) != 0` to `... == 0` and see if `handle_error()` catches something strange?

And `yz` is your actual username right? None of those is a special character?

Running out of ideas again...

**Comment by yermulnik** [comment] 2016-02-16 20:10
Yep, `yz` is my actual username and those are to Latin letters: `y` and `z` =)

```
22:09:01 [yz@local][w:4][j:0][~/.../CODE/firefox_decrypt]> env | egrep -i "lang|lc_"
LANG=ru_UA.UTF-8
MDM_LANG=ru_UA.UTF-8
LC_TIME=C
22:09:06 [yz@local][w:4][j:0][~/.../CODE/firefox_decrypt]> locale
LANG=ru_UA.UTF-8
LANGUAGE=
LC_CTYPE="ru_UA.UTF-8"
LC_NUMERIC="ru_UA.UTF-8"
LC_TIME=C
LC_COLLATE="ru_UA.UTF-8"
LC_MONETARY="ru_UA.UTF-8"
LC_MESSAGES="ru_UA.UTF-8"
LC_PAPER="ru_UA.UTF-8"
LC_NAME="ru_UA.UTF-8"
LC_ADDRESS="ru_UA.UTF-8"
LC_TELEPHONE="ru_UA.UTF-8"
LC_MEASUREMENT="ru_UA.UTF-8"
LC_IDENTIFICATION="ru_UA.UTF-8"
LC_ALL=
```

**Comment by Unode** [comment] 2016-02-16 21:48
So `utf8` is correct.

Other than trying to replace the `!= 0` on the `if` statements that call `NSS` by `== 0` (lines 151, 166, and 200) and checking if `handle_error()` catches something strange, I'm out of ideas again... :disappointed:

**Comment by yermulnik** [comment] 2016-02-16 21:55
Line 200 is `if NSS.PK11SDR_Decrypt(byref(username), byref(outuser), None) == -1:`, so I changed `==` to `!=`

```
23:53:45 [yz@local][w:4][j:1][~/.../CODE/firefox_decrypt]> ./firefox_decrypt.py
Select the Firefox profile you wish to decrypt
1 -> bgpdiy8n.default-1373553171844
Choice: 1

Master Password for profile /home/yz/.mozilla/firefox/bgpdiy8n.default-1373553171844:
2016-02-16 23:53:51,882 - ERROR - Couldn't initialize NSS
```
Unfortunately =(

**Comment by Unode** [comment] 2016-02-16 22:55
One more code change for a little bit more output. Though I'm not sure it will help given you already identified some issue with the initialization.

**Comment by yermulnik** [comment] 2016-02-17 15:15
```
Select the Firefox profile you wish to decrypt
1 -> bgpdiy8n.default-1373553171844
Choice: 1

Master Password for profile /home/yz/.mozilla/firefox/bgpdiy8n.default-1373553171844:
2016-02-17 17:14:39,542 - ERROR - Passwords protected by a Master Password!
```
=(

**Comment by Unode** [comment] 2016-02-17 15:16
Can you run it with `-vv`. I'm interested in the return codes of each step.

**Comment by yermulnik** [comment] 2016-02-17 15:21
[firefox_decrypt.log.txt](https://github.com/Unode/firefox_decrypt/files/134554/firefox_decrypt.log.txt)

**Comment by Unode** [comment] 2016-02-17 15:26
Sorry I meant `python firefox_decrypt.py -vv` .
Looks like you used `python -vv firefox_decrypt.py` and the `-vv` flag is being read by python instead of the script.

**Comment by yermulnik** [comment] 2016-02-17 15:34
[firefox_decrypt.log.txt](https://github.com/Unode/firefox_decrypt/files/134577/firefox_decrypt.log.txt)

**Comment by Unode** [comment] 2016-02-17 16:16
That last error message. Could it be the same problem from before? The one where you identified a missing library with `strace`?

As it looks right now, I'm not sure the problem is something I can fix.
It seems something is wrong with the local nss library. I tried compiling the same version you have and I can't reproduce the problem.

So we have 2 options:

1. Repeat the same procedure you did some time ago using `strace` to check (and fix) `libnssckbi.so` or some other cause of library failure? (At some point you had the `database is an old format` error)
2. Compile libnss manually and point the script to the compiled library instead of the system one.

If you want to compile nss you can follow these instructions:

* Download the same version you have on your system from https://ftp.mozilla.org/pub/security/nss/releases/NSS_3_19_2_RTM/src/nss-3.19.2-with-nspr-4.10.8.tar.gz
* Extract, chdir into `nss-3.19.2/nss` and run `USE_64=1 make nss_build_all` (omit `USE_64=1` if your python installation is 32bits)
* Edit firefox_decrypt.py and change the line containing `nssname = "libnss3.so"` to `nssname = "/full/path/to/nss-3.19.2/dist/Linux.../lib/libnss3.so"`.

If after compiling it still fails. I would then try with a newer version of nss. I have 3.21 on my system right now. If this also fails then I really don't know what is wrong and the only way I could debug further would be to reproduce the problem locally.

In any case, thanks for all the effort. You have been amazingly helpful and patient.

**Comment by Unode** [comment] 2016-04-17 20:41
Hi George,

So a test suite is now in place and so far the simple tests work.
Feel free to fork and see if you can create a test that fails on Travis.
If you do, please reopen this issue.

In the meantime I'll close it as I haven't been able to reproduce the problem so far.

Thanks again for all the effort.

**Closed by Unode** 2016-04-17 20:41 UTC
Labels: nss-bug, works-for-me
