### ISSUE TITLE
Segfault when interacting with libnss

### ISSUE THREAD

**Issue by sedrubal** [Unode/firefox_decrypt#2] opened 2016-01-08 18:12 UTC
I get a segfault in [line 119](https://github.com/Unode/firefox_decrypt/blob/master/firefox_decrypt.py#L119). Do you know whats wrong?

**Comment by Unode** [comment] 2016-01-09 02:59
Can you give some information?
What operating system? Version of Python? Version of Firefox or libnss? Using the sqlite or json database?
Can you also paste the output (hide your login/passwords) and the traceback if you get one.

At this stage I have no idea what could be wrong. I've never experienced a segfault with this script.

**Comment by sedrubal** [comment] 2016-01-09 04:55
Oh sorry, of course:

 - Fedora:23
 - Python 2.7.10 (python-2.7.10-8.fc23.x86_64)
 - Firefox 43.0.3 (firefox-43.0.3-1.fc23.x86_64)
 - nss 3.21.0 (nss-3.21.0-1.1.fc23.x86_64)
 - It seems to crash even before choosing sqlite or json...
 - There is no traceback, all I can read is:

```
Select the Firefox profile you wish to decrypt
1 -> xxxxxxxx.default
2 -> xxxxxxxx.dev-edition-default
Choice: 1

Master Password for profile /home/xxxxxxxx/.mozilla/firefox/xxxxxxxxx.default: 
Segmentation fault (core dumped)
```

So it looks like a bug in nss?

**Comment by Unode** [comment] 2016-01-11 15:38
Hi sedrubal,

Could you try downgrading nss to version 3.20.1 or anything before 3.21.0?
It might be an API change but I don't yet have a functional nss 3.21.0 on my system that I can test. Will try later.

**Comment by Unode** [comment] 2016-01-19 17:11
Hi sedrubal,

Finally managed to compile and test nss 3.21.0. And with the manually compiled version I didn't get any weird behaviour nor segfault.

Could you run `strace firefox_decrypt ...` and upload the output somewhere? Again, make sure to mask any sensitive information.

**Comment by sedrubal** [comment] 2016-01-20 04:33
Sorry for the delay... I tested it now on `fedora:22` with `nss-3.20.0` and now it's working brilliant.

This are the last 120 lines of the strace on fedora:23:

```strace
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f3b58fc0000
read(3, "[General]\nStartWithLastProfile=1"..., 4096) = 188
read(3, "", 4096)                       = 0
close(3)                                = 0
munmap(0x7f3b58fc0000, 4096)            = 0
write(2, "Select the Firefox profile you w"..., 47Select the Firefox profile you wish to decrypt
) = 47
write(2, "1 -> avlevi2g.default\n", 221 -> avlevi2g.default
) = 22
write(2, "2 -> 3gd3g4gs.dev-edition-defaul"..., 342 -> 3gd3g4gs.dev-edition-default
) = 34
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
write(2, "Choice: ", 8Choice: )                 = 8
fstat(0, {st_mode=S_IFCHR|0600, st_rdev=makedev(136, 0), ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f3b58fc0000
read(0, "1\n", 1024)                    = 2
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
open("/dev/tty", O_RDWR|O_NOCTTY)       = 3
fstat(3, {st_mode=S_IFCHR|0666, st_rdev=makedev(5, 0), ...}) = 0
fcntl(3, F_GETFL)                       = 0x8002 (flags O_RDWR|O_LARGEFILE)
ioctl(3, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(3, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(3, SNDCTL_TMR_CONTINUE or TCSETSF, {B38400 opost isig icanon -echo ...}) = 0
write(3, "\n", 1)                       = 1
write(3, "Master Password for profile /hom"..., 72) = 72
read(3, "passwordpassword\n", 8192)           = 11
ioctl(3, TCGETS, {B38400 opost isig icanon -echo ...}) = 0
ioctl(3, SNDCTL_TMR_CONTINUE or TCSETSF, {B38400 opost isig icanon echo ...}) = 0
write(3, "\n", 1)                       = 1
close(3)                                = 0
gettid()                                = 16105
rt_sigaction(SIGPIPE, {SIG_IGN, [], SA_RESTORER, 0x7f3b587cc9f0}, NULL, 8) = 0
open("/lib64/libsoftokn3.so", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0pC\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=269680, ...}) = 0
mmap(NULL, 2357840, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f3b4e414000
mprotect(0x7f3b4e452000, 2097152, PROT_NONE) = 0
mmap(0x7f3b4e652000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x3e000) = 0x7f3b4e652000
close(3)                                = 0
mprotect(0x7f3b4e652000, 4096, PROT_READ) = 0
open("/lib64/libnssdbm3.so", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P1\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=142392, ...}) = 0
mmap(NULL, 2233520, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f3b4e1f2000
mprotect(0x7f3b4e212000, 2097152, PROT_NONE) = 0
mmap(0x7f3b4e412000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x20000) = 0x7f3b4e412000
close(3)                                = 0
mprotect(0x7f3b4e412000, 4096, PROT_READ) = 0
stat("/home/user/.mozilla/firefox/avlevi2g.default/secmod.db", {st_mode=S_IFREG|0600, st_size=16384, ...}) = 0
open("/home/user/.mozilla/firefox/avlevi2g.default/secmod.db", O_RDONLY) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
read(3, "\0\6\25a\0\0\0\2\0\0\4\322\0\0\20\0\0\0\0\f\0\0\1\0\0\0\1\0\0\0\0\10"..., 260) = 260
lseek(3, 4096, SEEK_SET)                = 4096
read(3, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 4096) = 4096
lseek(3, 8192, SEEK_SET)                = 8192
read(3, "\2\0\344\17\24\r\n\r\24\r\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 4096) = 4096
close(3)                                = 0
open("/lib64/libfreebl3.so", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0009\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=502088, ...}) = 0
mmap(NULL, 2606920, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f3b4df75000
mprotect(0x7f3b4dfec000, 2093056, PROT_NONE) = 0
mmap(0x7f3b4e1eb000, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x76000) = 0x7f3b4e1eb000
mmap(0x7f3b4e1ee000, 14152, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f3b4e1ee000
close(3)                                = 0
mprotect(0x7f3b4e1eb000, 8192, PROT_READ) = 0
open("/dev/urandom", O_RDONLY)          = 3
read(3, "\200=\\\26G|\265\371:\200<\325\300\360!\260\217\200\227h\206\v\2721\250\263\301)VP\350\302"..., 110) = 110
close(3)                                = 0
sysinfo({uptime=371354, loads=[61184, 61056, 62848], totalram=8248606720, freeram=222523392, sharedram=610398208, bufferram=200876032, totalswap=8464101376, freeswap=8226590720, procs=855, totalhigh=0, freehigh=0, mem_unit=1}) = 0
uname({sysname="Linux", nodename="centaurus.sedrubal.de", ...}) = 0
sysinfo({uptime=371354, loads=[61184, 61056, 62848], totalram=8248606720, freeram=222523392, sharedram=610398208, bufferram=200876032, totalswap=8464101376, freeswap=8226590720, procs=855, totalhigh=0, freehigh=0, mem_unit=1}) = 0
stat("/dev/urandom", {st_mode=S_IFCHR|0666, st_rdev=makedev(1, 9), ...}) = 0
open("/dev/urandom", O_RDONLY)          = 3
read(3, "\362#\372\264\350\347\37\6k\276I+\303\347-\251\256\"at\237\7<\271\225\366\235\f\370\372\367\206"..., 1024) = 1024
close(3)                                = 0
stat("/etc/passwd", {st_mode=S_IFREG|0644, st_size=2997, ...}) = 0
open("/etc/passwd", O_RDONLY)           = 3
read(3, "root:x:0:0:root:/root:/bin/bash\n"..., 8192) = 2997
open("/dev/urandom", O_RDONLY)          = 4
read(4, "T\326Rhm\203\230\244\241 *9\205 \245\3213\354\216\5_.\310\16\2574 \"LO\373\256"..., 55) = 55
close(4)                                = 0
open("/dev/urandom", O_RDONLY)          = 4
read(4, "\2166`\347S;\366\321\262\35^Jq\312\3123\23\367]\224;\216[\315\301\343C\340e\" \35"..., 55) = 55
close(4)                                = 0
read(3, "", 8192)                       = 0
close(3)                                = 0
stat("/etc/utmp", 0x7fff306ddb00)       = -1 ENOENT (No such file or directory)
stat("/tmp", {st_mode=S_IFDIR|S_ISVTX|0777, st_size=720, ...}) = 0
open("/tmp", O_RDONLY)                  = 3
read(3, 0x7fff306ddb90, 8192)           = -1 EISDIR (Is a directory)
close(3)                                = 0
stat("/var/tmp", {st_mode=S_IFDIR|S_ISVTX|0777, st_size=4096, ...}) = 0
open("/var/tmp", O_RDONLY)              = 3
read(3, 0x7fff306ddb90, 8192)           = -1 EISDIR (Is a directory)
close(3)                                = 0
stat("/usr/tmp", {st_mode=S_IFDIR|S_ISVTX|0777, st_size=4096, ...}) = 0
open("/usr/tmp", O_RDONLY)              = 3
read(3, 0x7fff306ddb90, 8192)           = -1 EISDIR (Is a directory)
close(3)                                = 0
stat("/home/user/.mozilla/firefox/avlevi2g.default/cert8.db", {st_mode=S_IFREG|0600, st_size=655360, ...}) = 0
open("/home/user/.mozilla/firefox/avlevi2g.default/cert8.db", O_RDONLY) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
read(3, "\0\6\25a\0\0\0\2\0\0\4\322\0\0@\0\0\0\0\16\0\0\1\0\0\0\1\0\0\0\0\10"..., 260) = 260
lseek(3, 147456, SEEK_SET)              = 147456
read(3, "\34\0\367?\364?x?v:\2719.5\0065}4f4\0334\2323B-\371,*,\305+"..., 16384) = 16384
stat("/home/user/.mozilla/firefox/avlevi2g.default/key3.db", {st_mode=S_IFREG|0600, st_size=16384, ...}) = 0
open("/home/user/.mozilla/firefox/avlevi2g.default/key3.db", O_RDONLY) = 4
fcntl(4, F_SETFD, FD_CLOEXEC)           = 0
read(4, "\0\6\25a\0\0\0\2\0\0\4\322\0\0\20\0\0\0\0\f\0\0\1\0\0\0\1\0\0\0\0\10"..., 260) = 260
brk(NULL)                               = 0x5557fca41000
brk(0x5557fca62000)                     = 0x5557fca62000
lseek(4, 4096, SEEK_SET)                = 4096
read(4, "\10\0\371\17\370\17\370\16\315\t\277\t\213\t\200\tl\tV\tl\t\377\377\377\377\377\377\377\377\377\377"..., 4096) = 4096
open("/home/user/.mozilla/firefox/avlevi2g.default/libnssckbi.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0xfffffffffca42f28} ---
+++ killed by SIGSEGV (core dumped) +++
```

**Comment by Unode** [comment] 2016-01-20 11:39
So looking at the trace it seems like it fails somewhere around initialization of libnss. Yet it didn't segfault on my system. It might be something specific to the versions of the libraries in fedora on whatever patches they added on to them.

I'll add some more debugging info to the script and see if I can reproduce it on Fedora. Might take some time...

Thanks

**Comment by sedrubal** [comment] 2016-01-20 14:31
Ah ok. But usually fedora doesn't add any patches to packages but they take a program as is and pack it into rpms. But maybe they did on libnss...

If you don't want to, you don't have to fix it as I could already extract my passwords... ;)

**Comment by Unode** [comment] 2016-01-21 10:48
Hi sedrubal,

Tried a fresh updated fedora 22 virtual machine yesterday.
Out of the box everything worked. No segfaults.

Closing it as I couldn't reproduce it on a similar system.

**Comment by sedrubal** [comment] 2016-01-21 11:09
Yes, on f:22 it's working but on f:23 it's not working... (If you use docker, you don"t have to setup a vm ;) ). But it's ok to close it...

**Comment by Unode** [comment] 2016-01-21 14:35
You are right it does segfault on Fedora:23 and I was able to get some info out of it.
Will keep you posted.

**Comment by Unode** [comment] 2016-04-17 20:42
Ok so this is clearly a problem introduced by how Fedora packaged nss.
Compiling nss from source works.

I'm closing this as it's not something I can fix from this side.

**Closed by Unode** 2016-04-17 20:42 UTC
Labels: nss-bug, works-for-me

**Comment by sedrubal** [comment] 2016-04-17 22:16
Ok. Thanks for debugging ;)
