### ISSUE TITLE
Password decryption failed. Passwords protected by a Master Password!

### ISSUE THREAD

**Issue by kirsn** [unode/firefox_decrypt#25] opened 2018-05-07 12:43 UTC
Hello,

This issue is similar to #3 
My system info:
Windows 10, 64 bit
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)]
Firefox 59.0.3 (64-bit)

Have attached the detailed log: [decrypt_output.log](https://github.com/unode/firefox_decrypt/files/1979849/decrypt_output.log)

Please let me know if you require any more details.

**Comment by unode** [comment] 2018-05-07 13:46
Hi @kirsn,

In your case it seems the problem is that the script didn't find `libnss`.

Seeing that you have Firefox 64bits, can you tell me the full path where do you have Firefox installed (something like `C:\Program Files\Firefox` and also if you find a `nss3.dll` file on this folder?

**Comment by kirsn** [comment] 2018-05-07 16:25
Hello @unode, thanks for your prompt response. 

Yes, the nss3.dll is available in this path: C:\Program Files\Mozilla Firefox\nss3.dll . The log file has a line where it states `Loading NSS library from C:\Program Files\Mozilla Firefox\nss3.dll` . So am not sure whey the log ends with this message `PR_LOAD_LIBRARY_ERROR: Failure to load dynamic library`.

**Comment by unode** [comment] 2018-05-07 21:57
Sounds like a fun endeavour. I've never tried to create entries using `NSSInteraction`.
Take your time.

I've also been considering migrating the test suite to Python in order to automate testing Windows too so this will be in line with that.

**Comment by kirsn** [comment] 2018-05-09 10:51
@unode, thanks for the details. 
I'll need some help with this work; especially around the API, and also to get some feedback on the direction am going in. Should I post my questions / comments here ... or is there an IRC / Gitter channel, or something equivalent that works for you?

**Comment by unode** [comment] 2018-05-09 15:56
As for API, you will likely need [PK11SDR_Encrypt](https://dxr.mozilla.org/mozilla-beta/source/security/nss/lib/pk11wrap/pk11sdr.h) and [NSS_InitReadWrite](https://dxr.mozilla.org/mozilla-beta/source/security/nss/lib/nss/nssinit.c#830) instead of `NSS_Init` which is what the current code uses.
Then to set a master password you probably need [InitPW](https://dxr.mozilla.org/mozilla-beta/source/security/nss/cmd/modutil/pk11.c#676) or [ChangePW](https://dxr.mozilla.org/mozilla-beta/source/security/nss/cmd/modutil/pk11.c#709).

Finally to add new records, you'll have to create an interface to write `logins.json` yourself since this is Firefox/Thunderbird/... specific.

So far the code initializes a different interface depending on Firefox version (`JSON`, `SQLite`,...). You can skip SQLite and focus on `JSON` which covers most recent Firefox versions. Aiming at having QuickCheck/hypothesis tests for Firefox 59+ should be sufficient.

**Comment by unode** [comment] 2018-05-17 18:33
@kirsn can you check if the commit above changed anything for you?

**Comment by unode** [comment] 2018-05-18 10:42
@kirsn In the original log file you masked your username.
Can you say if you have non-ASCII characters in there or if the Windows version you are using is non-English?

Thanks

**Comment by kirsn** [comment] 2018-05-18 16:19
@unode , apologies for the delayed reply.
The usernames are plain ASCII. And my locale is en_US. 

Running: `python -c "import sys; print sys.stdin.encoding"` displays `cp437`

Also. took a look at the commit from above (didn't try it out, but just looked at the code), and it seems to address `sqllite` related changes. 
I haven't made progress on the *hypothesis* related code - hope to get back to it this week.

**Comment by unode** [comment] 2018-05-21 00:35
@kirsn #28 was fixed and reported success. I think that fix might also apply here. Would you mind giving it another try?

If this now works for you, would you mind renaming the issue to reflect the work on hypothesis testing. Thanks.

**Comment by kirsn** [comment] 2018-05-21 05:50
@unode tried the following, but no luck.
First `git clone` the repo, and use code from trunk.

- Trial 1: run without specifying the profile path -- [without-specific-profile-path.txt](https://github.com/unode/firefox_decrypt/files/2021358/without-specific-profile-path.txt)
- Trial 2: run with specifying the profile path `-profile` option -- [with-specific-profile-path.txt](https://github.com/unode/firefox_decrypt/files/2021359/with-specific-profile-path.txt)
- Trial 3: `cd` to the profile path, and run the code from there -- [run-from-inside-specific-profile-path.txt](https://github.com/unode/firefox_decrypt/files/2021357/run-from-inside-specific-profile-path.txt)
- Trial 4: I took the latest [commit](https://github.com/unode/firefox_decrypt/blob/d349dd157e1b3c061fe229537d5ff607ec7684c7/firefox_decrypt.py), and tried. Result was the same as `Trial 3` above.

A few other things:
- Am using Firefox Nightly.
- On line https://github.com/unode/firefox_decrypt/blob/d349dd157e1b3c061fe229537d5ff607ec7684c7/firefox_decrypt.py#L812 should be `parser.add_argument("-profile" ... ` ?

In any case, I'll open a separate issue to track the hypothesis-tests?

**Comment by unode** [comment] 2018-05-22 01:05
Thanks for the very comprehensive report!

I'm not familiar with how Firefox Nightly installs on Windows.
Checking online it seems it defaults to installing on `C:\Program Files\Nightly` (or `Program Files (x86)` if 32bits).
I've just pushed a commit that adds these paths to the search list. If you are using these locations Trial 1 and 2 should now at least find NSS. They may still fail if something else is amiss.

`profile` is supposed to be [the place where you have your Firefox settings](http://kb.mozillazine.org/Profile_folder_-_Firefox).
It was defined as `parser.add_argument("profile"...` so that you can launch with `firefox_decrypt.py C:\Users\Admin\AppData\Roaming\Mozilla\Firefox` instead of `firefox_decrypt.py --profile C:\Users\Admin\AppData\Roaming\Mozilla\Firefox\`. The profile path is a pretty crucial piece of information so it made sense to have it as a positional instead of `--optional` argument.
Strictly speaking it's not required so having it as `--profile` would be more consistent with convention but who wants to type `--profile` every time :smile: .

Since in your case it seems the script is failing to find (Trial 1 and 2) or failing to interact with `nss3.dll` (Trial 3 and 4).

1. Could you add a "Trial 5" where you do `cd <where you installed Firefox>`, check that `nss3.dll` exists in that location and launch `firefox_decrypt.py` from there?

If this works then it's clear that the problem is locating `NSS` or one of its dependencies.

It's curious that in Trial 3 and 4 it seems to find `nss3.dll` but doesn't in Trial 1 and 2.
I'm a little surprised by this since specifying a profile path shouldn't affect how `nss3.dll` is loaded but your tests seem to point otherwise. Not sure what to make of this.
From the logs I would assume that there is a `nss3.dll` in your profile folder but this would be unusual.

2. Could you run a system-wide search for `nss3.dll` and report all locations found?

Furthermore Trial 1 and 2 both fail on the hardcoded default installation paths which is consistent with your Firefox installation living elsewhere. If this is the only problem "Trial 5" described above should succeed (at least up to finding NSS).

**Comment by kirsn** [comment] 2018-05-22 16:43
A copy of `nss3.dll` lives in `C:\program files\Firefox Nightly`.
I also see that there are several `nss3.dll`s in my system - installed folders of Mozilla Thunderbird folder,  Pidgin, Tor Browser, and LibreOffice.

My trials 3 & 4 picked up the `nss3.dll`, in Nightly, because I ran the code from within the `C:\program files\Firefox Nightly` folder. I mistakenly called this the *profile* path, when I meant the *installed* path. Sorry, for the confusion. So Trial 5 is the same as Trials 3 & 4.

Noted the purpose of the `profile` option, and how to use it. Thanks for the description.

Is there anything else you would like me to try?

**Comment by unode** [comment] 2018-05-23 07:38
@kirsn thanks for the tests once again.

If you tried running from the installed path and it didn' work I'm afraid I'm out of ideas.
Other than mixing different architectures (32bit and 64bit) of Python and nss3.dll and issues with library search path, all of which have been excluded here, only encoding remains. That or something entirely new...

The last option would be to try running it from the several locations where nss3.dll exists but any success here would be as puzzling as a failure.

Perhaps we can try to get a reproducible failure on AppVeyor and go from there.
Thanks for the patience and all the help debugging this.

**Comment by kirsn** [comment] 2018-05-23 09:13
@unode no problem at all. I'll see if I can spend some more time to diagnose what could be wrong. Will update this issue, when I do. 

Not sure if you saw this, but the default encoding on my Windows10 box is `cp437`. Got this from running `python -c "import sys; print sys.stdin.encoding"`


Also, will open a separate issue (more as a task), to address the hypothesis based testing.

**Comment by npacific** [comment] 2020-06-13 07:13
Hi @unode ,

I reached your repository by looking a way to decrypt the mozilla passwords.
But the issue is i have protected my password with master password and now i have forgot the password.But  know some parts of the password.
So i want to launch  bruteforce attack on my file.

So what i have done was called 
nss.authenticate("1")
inside a for loop to lauch bruteforce  but i noticed after single call to nss.authenticate() we are not allowed to make other call.

It seems to be a lazy approach.

Can you through some light on the issue and help me way out.
So that i can get back my bunch of logins and passwords.

**Comment by unode** [comment] 2021-04-15 22:15
@kirsn It has been a couple of years but, if you are still using this, you may want to try the [UTF-8 mode](https://github.com/unode/firefox_decrypt#windows).

Otherwise, feel free to close the issue if no longer relevant.

**Closed** 2021-04-15 22:31 UTC
Labels: OS: Windows, bug, help wanted
