### ISSUE TITLE
Suggestion: Add the ability to specify a wordlist to bruteforce the Master Password

### ISSUE THREAD

**Issue by Reelix** [unode/firefox_decrypt#73] opened 2021-08-20 20:09 UTC
If you acquire a profile, you can currently brute-force the master password by going

`while read p; do echo $p | python3 firefox_decrypt.py /path/to/profile/here; done < /path/to/wordlist`

This option - Whilst viable for crackable passwords - Is obviously extremely inefficient due to the need to rerun the entire script per attempt.

I suggest the ability to add an option to specify a wordlist that the script will use to attempt to brute-force the master password if one exists.

**Comment by unode** [comment] 2021-08-22 22:44
Duplicate of #59 .

I'm sorry but any kind of password cracking is outside the scope of this tool.

**Closed by unode** 2021-08-22 22:44 UTC
