### ISSUE TITLE
ERROR - Passwords protected by a Master Password! It's not

### ISSUE THREAD

**Issue by doa379** [unode/firefox_decrypt#58] opened 2019-12-21 12:44 UTC
I am running on Linux Deb10 with Firefox-ESR (68). I get the error when trying to decrypt one of my profiles. There is no Master Password set in Firefox. I was able to decrypt another profile successfully.

```
Master Password for profile 
2019-12-21 12:38:35,926 - WARNING - Attempting decryption with no Master Password
2019-12-21 12:38:35,929 - ERROR - Password decryption failed. Passwords protected by a Master Password!
```

I ran tests/run_all:

```
decrypt/tests$ ./run_all
Passed:                            33
Failed:                             0
Unexpected successes:               0
Skipped:                            0
Expected failures:                  0
Runtime:                         2.09 seconds
```

**Comment by unode** [comment] 2019-12-31 17:01
Hi @doa379 , I'm using the same browser, version and also using a profile without password and cannot reproduce the problem.

Try running: `firefox_decrypt.py -vvv` for extra debugging information.

**Comment by iketanijus** [comment] 2020-01-06 10:08
Hello,
having exact same issue:

`$ ./run_all 
Passed:                            33
Failed:                             0
Unexpected successes:               0
Skipped:                            0
Expected failures:                  0
Runtime:                         1.73 seconds`

Please find output of -vvv flag:
https://pastebin.com/w2Ywuu2M

**Comment by unode** [comment] 2020-01-06 10:31
Hi @iketanijus,

From the log it's using `libnss` in the system library path. Do you by any chance have `libnss` installed through your system's package manager?

**Comment by iketanijus** [comment] 2020-01-06 10:34
Yes, I am using Slackware64-14.2 Linux. It has libnss3.so library provided by mozilla-nss-3.40.1-x86_64 package by default.

**Comment by unode** [comment] 2020-01-06 11:20
@iketanijus unless I'm misunderstanding. On the log, you didn't provide a master password but the username later on is still encrypted.

The tests above also passed so there is either a problem with your password input or your profile.

**Comment by iketanijus** [comment] 2020-01-06 12:25
Yes, I did not provide any password (just hit enter key on prompt), because that profile does not have any master password set actually. If I start Firefox from that profile, then I can see all the saved passwords without entering any master password. Still script complains that it's set for some reason, while it is certainly not.

**Comment by unode** [comment] 2020-01-06 12:54
I'm using `nss-3.46.1` here and everything works as expected. In the past we had users reporting problems when using `libnss` installed with the system's package manager. I've managed to reproduce it on Fedora but if compiled manually it worked fine so it was some kind of packaging incompatibility. In this case tests pass, so it seems like it's a different problem. 

A few steps you can try to troubleshoot this:
1. `chdir` into the folder where firefox/thunderbird is installed. Check that `libnss.so` is present and run `firefox_decrypt` from that location.
2. Create a new empty profile and add save a password without adding a master password. Check if the same problem appears.
3. Download NSS from [here](https://ftp.mozilla.org/pub/security/nss/releases/NSS_3_46_1_RTM/src/), compile manually and try running the script with this `libnss.so`.

If all still fail, could you share the profile you created in `2` so I can try to reproduce it on my side?

**Comment by unode** [comment] 2021-04-15 17:46
This should be fixed in the latest version.

**Closed by unode** 2021-04-15 17:46 UTC
