### ISSUE TITLE
Can not export passwords from Thunderbird 60

### ISSUE THREAD

**Issue by CoSoCo** [unode/firefox_decrypt#45] opened 2018-11-20 00:55 UTC
**Help us reproduce your problem**
I have installed Firefox 63 and Firefox ESR 52 in parallel on Ubuntu-64 18.04 de_DE.
I have installed Thunderbird 60.

**Describe the bug**
I can export passwords without problem from old backup profile (~1 year) which was used with old TB version 52 and also from both FF profiles version 52-ESR and 63.
I fail to export passwords from current profile of current TB version 60.
Maybe because I have installed Firefox ESR 52 in parallel, the wrong libnss3 is fetched.

**To Reproduce**
1. Launched `firefox_decrypt` with the following command-line arguments ...
./firefox_decrypt.py -f csv /home/ich/.thunderbird/Profiles/xxxxxxxx.default > TB_PW_2018-11-19.csv
2. Selected the profile directly by command-line argument
3. Typed in the master password ... yes. But I also tried with temporarily removing the master password.
4. Something didn't work (or worked differently from expected) ...
a) 2018-11-20 01:41:17,372 - ERROR - Master password is not correct
b) 2018-11-20 01:41:23,367 - WARNING - Attempting decryption with no Master Password
2018-11-20 01:41:23,374 - ERROR - Password decryption failed. Passwords protected by a Master Password!

**Comment by unode** [comment] 2018-11-20 08:57
Hi @CoSoCo 
Thanks for the report. You may be right in your diagnostic.

Can you try launching firefox_decrypt from the folder where you have the latest Firefox installed, or more precisely the folder containing `libnss3.so`. Does this help?

By default firefox_decrypt searches for libnss in the current folder before looking into system folders.

**Comment by CoSoCo** [comment] 2018-11-20 21:12
Here are the locations of different versions of libnss on my system:
```
$ find /usr -name "libnss3*" -ls
     5028   1008 -rw-r--r--   1 root     root      1029680 Jun 30 18:53 /usr/lib/firefox-esr/libnss3.so
    12359   1292 -rw-r--r--   1 root     root      1322264 Feb  5  2018 /usr/lib/x86_64-linux-gnu/libnss3.so
    28061    616 -rw-r--r--   1 root     root       627448 Okt 23 22:38 /usr/lib/firefox/libnss3.so
   536075    616 -rw-r--r--   1 root     root       627416 Sep 11 23:39 /usr/lib/thunderbird/libnss3.so
   531793      4 -rw-r--r--   1 root     root          708 Feb  5  2018 /usr/share/lintian/overrides/libnss3
   399509      4 drwxr-xr-x   2 root     root         4096 Apr 26  2018 /usr/share/doc/libnss3
```
I still have the error:
```
:/usr/lib/thunderbird$ ~/Installation/Mozilla/firefox_decrypt.py -f csv /home/ich/.thunderbird/Profiles/xxxxxxxx.default > ~/Installation/Mozilla/TB_PW_2018-11-19.csv
2018-11-20 22:05:57,326 - WARNING - profile.ini not found in /home/ich/.thunderbird/Profiles/xxxxxxxx.default
2018-11-20 22:05:57,326 - WARNING - Continuing and assuming '/home/ich/.thunderbird/Profiles/xxxxxxxx.default' is a profile location

Master Password for profile /home/ich/.thunderbird/Profiles/xxxxxxxx.default: 
2018-11-20 22:06:04,980 - ERROR - Password decryption failed. Passwords protected by a Master Password!
```

**Comment by CoSoCo** [comment] 2018-11-20 21:30
With deleted password I get:
```
:/usr/lib/thunderbird$ ~/Installation/Mozilla/firefox_decrypt.py -f csv /home/ich/.thunderbird/Profiles/xxxxxxxx.default > ~/Installation/Mozilla/TB_PW_2018-11-19.csv
2018-11-20 22:23:59,210 - WARNING - profile.ini not found in /home/ich/.thunderbird/Profiles/xxxxxxxx.default
2018-11-20 22:23:59,211 - WARNING - Continuing and assuming '/home/ich/.thunderbird/Profiles/xxxxxxxx.default' is a profile location

Master Password for profile /home/ich/.thunderbird/Profiles/xxxxxxxx.default: 
2018-11-20 22:24:00,328 - WARNING - Attempting decryption with no Master Password
2018-11-20 22:24:00,335 - ERROR - Password decryption failed. Passwords protected by a Master Password!
```

**Comment by unode** [comment] 2018-11-20 21:45
It's possible that this is another manifestation of https://github.com/unode/firefox_decrypt/issues/25 and locale related.

There's a couple of issues hitting this problem but I haven't found the time to fix it properly. There was some fixes to make it work on Windows but this had unwanted consequences on Linux.

So maybe, could you also try https://github.com/unode/firefox_decrypt/releases/tag/0.7.0 and let me know if it behaves better or the same?

**Comment by CoSoCo** [comment] 2018-11-20 22:35
I already used version 0.7.0 from here: https://github.com/unode/firefox_decrypt/blob/master/firefox_decrypt.py
Or is there a difference to the zipped version from your link?

**Comment by unode** [comment] 2018-11-21 12:24
Yes, there is. The latest master isn't 0.7.0 anymore although it still reports that.

**Comment by CoSoCo** [comment] 2018-11-21 22:22
OK. Also with the "true" version 0.7.0 from the zip I get the same errors.

**Comment by unode** [comment] 2018-11-21 22:57
Thanks for checking. Sad to hear that it doesn't work either.

> With deleted password I get:
> 
> ```
> :/usr/lib/thunderbird$ ~/Installation/Mozilla/firefox_decrypt.py -f csv /home/ich/.thunderbird/Profiles/xxxxxxxx.default > ~/Installation/Mozilla/TB_PW_2018-11-19.csv
> 2018-11-20 22:23:59,210 - WARNING - profile.ini not found in /home/ich/.thunderbird/Profiles/xxxxxxxx.default
> 2018-11-20 22:23:59,211 - WARNING - Continuing and assuming '/home/ich/.thunderbird/Profiles/xxxxxxxx.default' is a profile location

This is actually a successful execution. The warning is just because you specified the profile folder directly (as opposed to the folder containing `profile.ini`).
In the other cases it might be failing because an incorrect version of `nss3.so` is being picked up like you pointed out in your first comment.

By the way I noticed you didn't specify which Python version you are using. 
Do you get the same results with both Python 2.7 and 3.5 or above?

You can also increase verbosity by passing `-vv` which will tell you which library is being loaded. Search for `Loaded NSS` in the output.
If it's indeed loading an incorrect `libnss3.so` try forcing it to load different versions by changing to the directory like you did with thunderbird above or changing the code directly.

If your diagnostic is correct this probably means we need a better way to handle cases when multiple `libnss3.so` exist and the first pick is not compatible.

**Comment by CoSoCo** [comment] 2018-11-21 23:35
> > With deleted password I get:
> > ```
> > :/usr/lib/thunderbird$ ~/Installation/Mozilla/firefox_decrypt.py -f csv /home/ich/.thunderbird/Profiles/xxxxxxxx.default > ~/Installation/Mozilla/TB_PW_2018-11-19.csv
> > 2018-11-20 22:23:59,210 - WARNING - profile.ini not found in /home/ich/.thunderbird/Profiles/xxxxxxxx.default
> > 2018-11-20 22:23:59,211 - WARNING - Continuing and assuming '/home/ich/.thunderbird/Profiles/xxxxxxxx.default' is a profile location
> > ```
> 
> This is actually a successful execution. The warning is just because you specified the profile folder directly (as opposed to the folder containing `profile.ini`).

But 1 line after I also got:
```
Master Password for profile /home/ich/.thunderbird/Profiles/xxxxxxxx.default: 
2018-11-20 22:24:00,328 - WARNING - Attempting decryption with no Master Password
2018-11-20 22:24:00,335 - ERROR - Password decryption failed. Passwords protected by a Master Password!
```

> By the way I noticed you didn't specify which Python version you are using.

Python 2.7.15rc1

> You can also increase verbosity by passing `-vv` which will tell you which library is being loaded. Search for `Loaded NSS` in the output.
```
:~$ cd /usr/lib/thunderbird
:/usr/lib/thunderbird$ ~/Installation/Mozilla/firefox_decrypt-0.7.0.py -vv -f csv ~/.thunderbird/Profiles/xxxxxxxx.default > ~/Installation/Mozilla/TB_PW_2018-11-19.csv 
2018-11-22 00:23:17,429 - INFO - Running firefox_decrypt version: 0.7.0
2018-11-22 00:23:17,429 - DEBUG - Parsed commandline arguments: Namespace(choice=None, delimiter=';', export_pass=False, format='csv', interactive=True, list=False, pass_prefix=u'web', profile='/home/ich/.thunderbird/Profiles/xxxxxxxx.default', quotechar='"', tabular=False, verbose=2)
2018-11-22 00:23:17,430 - DEBUG - Skipping password store test, not exporting
2018-11-22 00:23:17,430 - DEBUG - Loading NSS library from libnss3.so
2018-11-22 00:23:17,431 - DEBUG - Reading profiles from /home/ich/.thunderbird/Profiles/xxxxxxxx.default/profiles.ini
2018-11-22 00:23:17,431 - WARNING - profile.ini not found in /home/ich/.thunderbird/Profiles/xxxxxxxx.default
2018-11-22 00:23:17,431 - WARNING - Continuing and assuming '/home/ich/.thunderbird/Profiles/xxxxxxxx.default' is a profile location
2018-11-22 00:23:17,432 - DEBUG - Initializing NSS with profile path '/home/ich/.thunderbird/Profiles/xxxxxxxx.default'
2018-11-22 00:23:17,437 - DEBUG - Initializing NSS returned 0
2018-11-22 00:23:17,437 - DEBUG - Retrieving internal key slot
2018-11-22 00:23:17,437 - DEBUG - Internal key slot <__main__.LP_PK11SlotInfo object at 0x7f0399a83290>

Master Password for profile /home/ich/.thunderbird/Profiles/xxxxxxxx.default: 
2018-11-22 00:24:05,819 - WARNING - Attempting decryption with no Master Password
2018-11-22 00:24:05,820 - DEBUG - Database location: /home/ich/.thunderbird/Profiles/xxxxxxxx.default/logins.json
2018-11-22 00:24:05,821 - INFO - Using /home/ich/.thunderbird/Profiles/xxxxxxxx.default/logins.json for credentials.
2018-11-22 00:24:05,821 - INFO - Decrypting credentials
2018-11-22 00:24:05,822 - DEBUG - Reading password database in JSON format
2018-11-22 00:24:05,825 - DEBUG - Decrypting username data 'MDIEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECCpiJYIT96YHBAhCTlcCzLhZqw=='
2018-11-22 00:24:05,830 - DEBUG - Decryption of data returned -1
2018-11-22 00:24:05,830 - ERROR - Password decryption failed. Passwords protected by a Master Password!
2018-11-22 00:24:05,830 - DEBUG - Error during a call to NSS library, trying to obtain error info
2018-11-22 00:24:05,831 - DEBUG - PR_LOAD_LIBRARY_ERROR: Failure to load dynamic library
```

**Comment by unode** [comment] 2018-11-21 23:44
Is by any chance `libnss3.so` a 32bit binary?
What does `file libnss3.so` say?

**Comment by CoSoCo** [comment] 2018-11-22 00:01
> Is by any chance `libnss3.so` a 32bit binary?

How can I test this?
> What does `file libnss3.so` say?

What you mean by that?

**Comment by CoSoCo** [comment] 2018-11-22 09:12
> What does `file libnss3.so` say?
Now I understand, that you meant this as command, sorry for my nail in the head.
```
:/usr/lib/thunderbird$ find /usr -name "libnss3*" -exec file {} \;
/usr/lib/firefox-esr/libnss3.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=b8884731b84a603880db77684c49a0dc0e0b23d1, stripped
/usr/lib/x86_64-linux-gnu/libnss3.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=67bf1422fd9344e7e61956ac58fe9b26d76b8874, stripped
/usr/lib/firefox/libnss3.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=2e7cb0613f11fda2d67ac15f5e78e84b003c51a0, stripped
/usr/lib/thunderbird/libnss3.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=3216776bc75c7f1527126911b8aa1e1675965bed, stripped
/usr/share/lintian/overrides/libnss3: ASCII text
/usr/share/doc/libnss3: directory
```

**Comment by unode** [comment] 2018-11-22 10:13
Ok that's not the problem either and I can't tell from your debugging output what could be wrong.
Specially since it also fails even when you remove the master password.

I currently don't have the time to look into it. Maybe mid December.

In the meanwhile you can try forcing it to run with the different `libnss3.so` on your system. In particular I'd expect `/usr/lib/x86_64-linux-gnu/libnss3.so` to be somewhat more reliable.
If neither works, it's quite possibly a locale related problem. Those are pending a fix too.
Running with Python 3 may also help.

Additionally, if you can reproduce the problem with a new Firefox or Thunderbird profile, could you attach this profile so I can test it from my side?

Thanks and sorry for the trouble.

**Comment by CoSoCo** [comment] 2018-11-22 13:59
Hi unode,
much thanks for your investigation and friendly communication.

I now have created a new TB profile with test account:
[yulgi7jw.Mozilla-Test.zip](https://github.com/unode/firefox_decrypt/files/2608297/yulgi7jw.Mozilla-Test.zip)
I have tested with:
/usr/lib/x86_64-linux-gnu/libnss3.so
/usr/lib/thunderbird/libnss3.so
Both work fine with `firefox_decrypt-0.7.0.py`.
So there seems something special with my normal profile, maybe uncommon characters.

**Comment by unode** [comment] 2018-11-22 14:05
Can you now add some password to this test profile in a way that it stops working?
If it is indeed some uncommon characters, I'd like to be able to reproduce this problem such that I can look into why it fails.

**Comment by CoSoCo** [comment] 2018-11-22 14:33
That seems difficult, because when I look at my logins and passwords, there are no special characters in my opinion.

I like to offer you another way. I could send you my key4.db and logins.json files via private email. So can you send me your email?

**Comment by unode** [comment] 2018-11-22 16:09
I don't feel comfortable receiving your entire password store for
obvious reasons  . Thanks for the vote of trust though.

I suggest you try making a copy of your profile, and removing or
modifying most passwords. Given your locale, I'd pay special attention
to the presence of umlauts or eszett in either passwords, logins or both.

If you are actually ok with sending your password store please use the
email alves.rjc@gmail.com (also used in the git commit history) and the
attached GPG public key which will allow you to send a fully encrypted
message.

**Comment by unode** [comment] 2018-11-22 16:12
Seems like attachments through email don't work. Here's the [public GPG key](https://github.com/unode/firefox_decrypt/files/2608744/0xA703C12A2FA65D04.txt).

**Comment by CoSoCo** [comment] 2018-11-22 19:03
> I suggest you try making a copy of your profile, and removing or modifying most passwords.

Let's try that first. If I remove the passwords, you would not have data ???
But modifying I don't know how to do, because "Saved Password Editor" is not working on TB 60 any more. Do you have a smart idea, how to manage that?

> Given your locale, I'd pay special attention to the presence of umlauts or eszett in either passwords, logins or both.

Yes, I know. I don't use them for logins and passwords.

**Comment by unode** [comment] 2019-06-10 20:20
I realize this has been pending on my side. After offline exchange I'm still missing some files so I couldn't inspect the password store.

I'm closing this as I can't troubleshoot or reproduce on my side.
Feel free to reopen if there's any additional info that might be useful for further diagnostic and sorry that I couldn't help further.

**Closed by unode** 2019-06-10 20:20 UTC
Labels: OS: Linux, bug
