### ISSUE TITLE
Release please (fixing an input selection bug)

### ISSUE THREAD

**Issue by hyiltiz** [unode/firefox_decrypt#34] opened 2018-07-10 07:13 UTC
The project README.md mentions `--pass-compat` flat, while the latest release `0.7.0` has no such support. It would be great to keep the released version in sync with the documentation. The master branch 2a317741f2bfebbbc0b70787855f8b59ff9519a8 didn't work on macOS: prompted two profiles for Firefox, but pressing `1` then pressing Enter simply repeated the prompt, stuck in a loop.

```BASH
~/D/firefox_decrypt-master $ python firefox_decrypt.py --export-pass 
Select the Firefox profile you wish to decrypt
1 -> Profiles/nmpnntrd.default
2 -> Profiles/gtd5qo9s.dev-edition-default
1
Select the Firefox profile you wish to decrypt
1 -> Profiles/nmpnntrd.default
2 -> Profiles/gtd5qo9s.dev-edition-default
2
Select the Firefox profile you wish to decrypt
1 -> Profiles/nmpnntrd.default
2 -> Profiles/gtd5qo9s.dev-edition-default

Traceback (most recent call last):
  File "firefox_decrypt.py", line 965, in <module>
    main()
  File "firefox_decrypt.py", line 935, in main
    profile = get_profile(basepath, args.interactive, args.choice, args.list)
  File "firefox_decrypt.py", line 822, in get_profile
    section = ask_section(profiles, choice)
  File "firefox_decrypt.py", line 717, in ask_section
    choice = raw_input()
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
```

**Comment by hyiltiz** [comment] 2018-07-10 07:16
This is fixed by explicitly calling `python3`.

**Comment by unode** [comment] 2018-07-12 02:35
With regards to `--pass-compat`, please check the [CHANGELOG](https://github.com/unode/firefox_decrypt/blob/master/CHANGELOG.md).

As for documentation of 0.7 please check the README from the appropriate release/tag.
You can find 0.7 [here](https://github.com/unode/firefox_decrypt/blob/0.7.0/README.md).

The README in the master branch corresponds to the development version which is currently unstable. 

`--pass-compat` is an unreleased feature as found in the changelog.

---

As for the loop error, I cannot reproduce this behavior at all. What is your default python version?
Anything older than 2.7 is unsupported. Python 3 is recommended.

**Comment by hyiltiz** [comment] 2018-07-12 20:14
Oh, gotcha! Is there any way to generate a single file in the pass multiline format instead? Simply not using `--pass-compat` flag didn't seem to help, as it still produced a directory structure.

**Comment by unode** [comment] 2018-08-27 06:33
Sorry for the delay. I'm still unsure on what caused the parsing error and I haven't been able to reproduce this myself.
The only thought that comes to mind is that somehow the input was non-numeric, possibly encoding related.

Are you by any chance using a [double-byte encoding](https://en.wikipedia.org/wiki/DBCS) on your system?

Since you solved the problem by using Python 3 and this is now the recommended version I'm going to close this.
Feel free to reopen if you manage to reproduce this issue with Python 3.

**Closed by unode** 2018-08-27 06:33 UTC
Labels: OS: Mac

**Comment by unode** [comment] 2018-08-27 15:57
Ok, then I'm clueless as to what caused it...
